# Generated by Django 5.1.6 on 2025-02-16 12:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Connections',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('user_email', models.EmailField(max_length=254)),
                ('message', models.TextField()),
            ],
            options={
                'verbose_name': 'Connections',
                'verbose_name_plural': 'Connections',
                'db_table': 'connections',
            },
        ),
        migrations.CreateModel(
            name='OurTariffs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tariffs_title', models.CharField(blank=True, max_length=150, null=True)),
                ('tariffs_info', models.TextField(blank=True, null=True)),
                ('tariffs_price', models.CharField(blank=True, max_length=100, null=True)),
                ('tariffs_image', models.ImageField(blank=True, null=True, upload_to='', verbose_name='tariffs/%Y/%m/%d')),
            ],
            options={
                'verbose_name': 'Tariffs',
                'verbose_name_plural': 'Tariffs',
                'db_table': 'tariffs',
            },
        ),
        migrations.CreateModel(
            name='OurWorkers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('worker_name', models.CharField(blank=True, max_length=150, null=True)),
                ('worker_image', models.ImageField(blank=True, null=True, upload_to='workers/')),
                ('worker_info', models.TextField(blank=True, null=True)),
                ('worker_phone', models.CharField(blank=True, max_length=13, null=True)),
                ('worker_telegram', models.URLField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Workers',
                'verbose_name_plural': 'Workers',
                'db_table': 'workers',
            },
        ),
        migrations.CreateModel(
            name='Works',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('work_title', models.CharField(blank=True, max_length=250, null=True)),
                ('work_info', models.TextField(blank=True, null=True)),
                ('work_images', models.ImageField(blank=True, null=True, upload_to='', verbose_name='works/%Y/%m/%d')),
                ('work_files', models.FileField(blank=True, null=True, upload_to='', verbose_name='works_files/')),
                ('worker', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app_full.ourworkers')),
            ],
            options={
                'verbose_name': 'Works',
                'verbose_name_plural': 'Works',
                'db_table': 'works',
            },
        ),
    ]
